#!/bin/bash
# HELIX V3 - Manual Status Check Instructions

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  HELIX V3 - Netcup Server Status Check                  ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Deployment wurde hochgeladen!"
echo ""
echo "📋 MANUELLE SCHRITTE zur Verifizierung:"
echo ""
echo "1️⃣  Verbinde zum Server:"
echo "    ssh root@152.53.191.99"
echo "    Passwort: KkZrHw5wrJJnn6TH"
echo ""
echo "2️⃣  Navigiere zum Projekt:"
echo "    cd /opt/helix"
echo ""
echo "3️⃣  Prüfe PM2 Status:"
echo "    pm2 status"
echo ""
echo "4️⃣  Zeige Logs an:"
echo "    pm2 logs helix --lines 50"
echo ""
echo "5️⃣  Falls nicht gestartet, starte manuell:"
echo "    npm install --omit=dev"
echo "    pm2 start tsx --name helix -- server/index.ts"
echo "    pm2 save"
echo ""
echo "6️⃣  Prüfe Port-Binding:"
echo "    netstat -tlnp | grep 5000"
echo ""
echo "7️⃣  Teste Health-Endpoint:"
echo "    curl http://localhost:5000/health"
echo ""
echo "8️⃣  Falls Firewall-Problem:"
echo "    ufw allow 5000/tcp"
echo "    ufw reload"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🌐 Nach erfolgreichem Start:"
echo "   http://152.53.191.99:5000"
echo ""
echo "📊 Monitoring:"
echo "   pm2 monit"
echo ""
