import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  de: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.analytics': 'Berichte & Analysen',
    'nav.dataCollection': 'Datensammlung',
    'nav.newsletterAdmin': 'Newsletter-Verwaltung',
    'nav.emailManagement': 'Email-Verwaltung',
    'nav.knowledgeBase': 'Wissensdatenbank',
    'nav.regulatoryUpdates': 'Regulatorische Updates',
    'nav.legalCases': 'Rechtsprechung',
    'nav.globalApprovals': 'Globale Zulassungen',
    'nav.ongoingApprovals': 'Laufende Zulassungen',
    'nav.intelligentSearch': 'Intelligente Suche',
    'nav.syncManager': 'Sync-Verwaltung',
    'nav.globalSources': 'Globale Quellen',
    'nav.newsletterManager': 'Newsletter Manager',
    'nav.historicalData': 'Historische Daten',
    'nav.customerManagement': 'Kunden-Management',
    'nav.userManagement': 'Benutzerverwaltung',
    'nav.systemAdmin': 'System-Verwaltung',
    'nav.auditLogs': 'Audit-Protokolle',
    
    // Navigation Sections
    'nav.sections.overview': 'ÜBERSICHT & STEUERUNG',
    'nav.sections.dataManagement': 'DATENMANAGEMENT',
    'nav.sections.compliance': 'COMPLIANCE & REGULIERUNG',
    'nav.sections.approvals': 'ZULASSUNGEN & REGISTRIERUNG',
    'nav.sections.advanced': 'ERWEITERT',
    'nav.sections.projects': 'PROJEKTE & AKTEN',
    'nav.sections.standards': 'STANDARDS & NORMEN',

    // Assistants & Sub-Items
    'nav.regulatoryAssistant': 'Regulatory Assistent',
    'nav.approvalAssistant': 'Zulassungs-Assistent',
    'nav.projectAssistant': 'Projekt-Assistent',
    'nav.formAssistant': 'Formular-Assistent',
    'nav.projectOverview': 'Projektübersicht',
    'nav.newProject': 'Neue Projektakte',
    'nav.projectMDR': 'Projektakte (MDR)',
    'nav.globalPatents': 'Globale Patente',
    'nav.patentSearch': 'Patent-Suche',
    'nav.legalAssistant': 'Rechtsassistent',
    'nav.dataSourcesDetails': 'Datenquellen-Details',
    'nav.dataCollectionCenter': 'Datensammlungs-Center',
    'nav.advancedAnalysis': 'Erweiterte Auswertung',
    'nav.marketInsights': 'Markt & Insights',
    'nav.aiInsights': 'KI-Erkenntnisse',

    // Standards
    'nav.standards.iso': 'ISO Standards',
    'nav.standards.iec': 'IEC Standards',
    'nav.standards.astm': 'ASTM Standards',
    'nav.standards.en': 'EN Standards',
    'nav.standards.aami': 'AAMI Standards',
    'nav.standards.mdr': 'EU MDR 2017/745',

    // Sidebar UI
    'sidebar.search.title': 'Intelligente Suche',
    'sidebar.search.placeholder': 'Suche nach Regulierungen, Devices, Zulassungen...',
    'sidebar.search.hint': 'Drücken Sie Enter zum Suchen',
    'sidebar.systemStatus': 'System Status',
    'sidebar.dataSources': 'Datenquellen',
    'sidebar.active': '21 Aktiv',
    'sidebar.logout': 'System Logout',
    'sidebar.customerPortal': 'Kundenportal',
    'sidebar.openCustomerPortal': 'Customer Portal öffnen',
    'sidebar.profile': 'Profil',
    'sidebar.settings': 'Einstellungen',
    'sidebar.signOut': 'Abmelden',
    'sidebar.tenantLogin': 'Mandanten-Login',
    'sidebar.customerArea': 'Kundenbereich',
    'sidebar.supportChat': 'Support-Chat',
    'sidebar.openMenu': 'Menü öffnen',
    'sidebar.brandSubtitle': 'MedTech-Intelligenz',
    'sidebar.brandName': 'Helix',
    'sidebar.poweredBy': 'Bereitgestellt von Helix Platform',
    'sidebar.footerVersion': 'Helix Platform v2.0',
    'sidebar.footerCopyright': '© 2025 MedTech Intelligence',

    // Search
    'search.askQuestion': 'Frage stellen...',
    
    // Status
    'status.label': 'Status',
    'status.online': 'Online',
    'status.dataSources': '46 Datenquellen',
    
    // Common
    'common.search': 'Suchen',
    'common.loading': 'Wird geladen...',
    'common.error': 'Fehler',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.view': 'Anzeigen',
    'common.download': 'Herunterladen',
    'common.export': 'Exportieren',
    'common.filter': 'Filter',
    'common.all': 'Alle',
    'common.active': 'Aktiv',
    'common.inactive': 'Inaktiv',
    'common.pending': 'Ausstehend',
    'common.completed': 'Abgeschlossen',
    'common.date': 'Datum',
    'common.status': 'Status',
    'common.priority': 'Priorität',
    'common.region': 'Region',
    'common.category': 'Kategorie',
    'common.source': 'Quelle',
    'common.language': 'Sprache',
    
    // Dashboard
    'dashboard.title': 'Helix Regulatory Intelligence',
    'dashboard.subtitle': 'Comprehensive Medical Device Regulatory Platform',
    'dashboard.totalUpdates': 'Gesamt Updates',
    'dashboard.legalCases': 'Rechtsfälle',
    'dashboard.knowledgeArticles': 'Knowledge Articles',
    'dashboard.activeDataSources': 'Aktive Datenquellen',
    'dashboard.recentActivity': 'Aktuelle Aktivitäten',
    'dashboard.welcomeBack': 'Willkommen zurück',
    
    // Intelligent Search
    'search.title': 'Intelligente Suche',
    'search.subtitle': 'KI-gestützte Suche durch alle Helix-Datenquellen',
    'search.placeholder': 'z.B. "MDR-Anforderungen für Klasse III Geräte"',
    'search.searching': 'Suche...',
    'search.results': 'Suchergebnisse',
    'search.aiAnswer': 'KI-Antwort',
    'search.noResults': 'Keine Ergebnisse gefunden',
    'search.confidence': 'Vertrauen',
    'search.relevance': 'Relevanz',
    'search.databaseResults': 'Eigene Daten',
    'search.aiResults': 'KI-Ergebnis',
    
    // Analytics
    'analytics.title': 'Analytics Intelligence',
    'analytics.subtitle': 'Umfassende Analyse der regulatorischen Datenlandschaft',
    'analytics.totalUpdates': 'Gesamt Updates',
    'analytics.pendingApprovals': 'Wartende Genehmigungen',
    'analytics.regionalDistribution': 'Regionale Verteilung',
    'analytics.categoryBreakdown': 'Kategorie Breakdown',
    'analytics.sourcePerformance': 'Datenquellen Performance',
    
    // Knowledge Base
    'knowledge.title': 'Wissensdatenbank',
    'knowledge.subtitle': 'Medizintechnik Wissensartikel aus authentischen Quellen',
    'knowledge.totalArticles': 'Gesamt Artikel',
    'knowledge.activeSources': 'Aktive Quellen',
    'knowledge.regions': 'Regionen',
    'knowledge.languages': 'Sprachen',
    'knowledge.searchPlaceholder': 'Nach Artikeln suchen...',
    
    // Newsletter Admin
    'newsletter.title': 'Newsletter Administration',
    'newsletter.subtitle': 'Verwalten Sie authentische Newsletter-Quellen',
    'newsletter.addSource': 'Neue Quelle hinzufügen',
    'newsletter.configuredSources': 'Konfigurierte Newsletter-Quellen',
    'newsletter.authenticSources': 'Authentische Newsletter-Quellen',
    
    // Data Collection
    'dataCollection.title': 'Datensammlung',
    'dataCollection.subtitle': 'Zentrale Verwaltung von {{count}} Datenquellen und Sync-Prozessen',
    'dataCollection.activeSources': 'Aktive Quellen',
    'dataCollection.syncStatus': 'Sync-Status',
    'dataCollection.lastSync': 'Letzter Sync',
    'dataCollection.syncNow': 'Jetzt synchronisieren',
    'dataCollection.manageSource': 'Quelle verwalten',
    'dataCollection.newsletterSources': '📧 Newsletter-Quellen',
    'dataCollection.runningSyncs': 'Laufende Syncs',
    'dataCollection.pendingSyncs': 'Ausstehende Syncs',
    'dataCollection.recentSyncs': 'Kürzliche Syncs',
    
    // Regulatory Updates
    'regulatory.title': 'Regulatorische Updates',
    'regulatory.subtitle': 'Aktuelle Vorschriften und Richtlinien für Medizinprodukte',
    'regulatory.region': 'Region',
    'regulatory.authority': 'Behörde',
    'regulatory.published': 'Veröffentlicht',
    'regulatory.viewDetails': 'Details anzeigen',
    'regulatory.searchUpdates': 'Updates durchsuchen...',
    'regulatory.allRegions': 'Alle Regionen',
    'regulatory.allAuthorities': 'Alle Behörden',
    'regulatory.allCategories': 'Alle Kategorien',
    'regulatory.allPriorities': 'Alle Prioritäten',
    'regulatory.allTypes': 'Alle Typen',
    'regulatory.resetFilters': 'Filter zurücksetzen',
    'regulatory.loadingUpdates': 'Lade Updates...',
    'regulatory.noUpdatesFound': 'Keine Updates gefunden',
    'regulatory.tryDifferentSearch': 'Versuchen Sie eine andere Suchanfrage oder Filter',
    'regulatory.resultsCount': 'Ergebnissen',
    'regulatory.updatesOf': 'von',
    'regulatory.newBadge': 'Neu',
    'regulatory.type.approval': 'Zulassungen',
    'regulatory.type.regulation': 'Verordnungen',
    'regulatory.type.guidance': 'Leitlinien',
    'regulatory.type.standard': 'Standards',
    'regulatory.type.alert': 'Warnungen',
    'regulatory.tab.document': 'Dokument',
    'regulatory.tab.action': 'Handlungsbedarf',
    'regulatory.tab.implementation': 'Umsetzung',
    'regulatory.tab.control': 'Dokumentensteuerung',
    'regulatory.tab.metadata': 'Metadaten',
    'regulatory.documentDetails': 'Dokumenten-Details',
    'regulatory.documentType': 'Dokumententyp',
    'regulatory.jurisdiction': 'Zuständigkeit',
    'regulatory.kNumber': 'K-Nummer',
    'regulatory.applicant': 'Antragsteller',
    'regulatory.productCode': 'Produktcode',
    'regulatory.publishedAt': 'Veröffentlicht',
    'regulatory.effectiveFrom': 'Gültig ab',
    'regulatory.descriptionJustification': 'Beschreibung & Begründung',
    'regulatory.descriptionHint': 'Diese Beschreibung erklärt die Hintergründe, Gründe und Auswirkungen dieser regulatorischen Änderung.',
    'regulatory.sourcesAndDocs': 'Quellen & Offizielle Dokumente',
    'regulatory.dataSource': 'Datenquelle',
    'regulatory.officialSource': 'Offizielle Quelle',
    'regulatory.documentDownload': 'Dokument-Download',
    'regulatory.downloadOfficialDoc': 'Offizielles Dokument herunterladen',
    'regulatory.accompanyingDocs': 'Begleitdokumente & Leitfäden',
    'regulatory.openDocument': 'Dokument öffnen',
    'regulatory.fullDocumentContent': 'Vollständiger Dokumenten-Inhalt',
    'regulatory.actionRequired': 'Handlungsbedarf erforderlich',
    'regulatory.measuresRequired': 'Maßnahmen erforderlich für Compliance',
    'regulatory.deadline': 'Frist',
    'regulatory.affectedProducts': 'Betroffene Produkte',
    'regulatory.guidelineDocuments': 'Leitliniendokumente',
    'regulatory.noActionRequired': 'Kein Handlungsbedarf',
    'regulatory.noImmediateMeasures': 'Dieses Dokument erfordert keine unmittelbaren Maßnahmen.',
    'regulatory.implementationGuide': 'Umsetzungsleitfaden',
    'regulatory.noImplementationGuide': 'Keine Umsetzungsanleitung verfügbar',
    'regulatory.timeframe': 'Zeitlicher Rahmen',
    'regulatory.estimatedTime': 'Geschätzte Umsetzungszeit',
    'regulatory.documentLifecycle': 'Dokumenten-Lifecycle',
    'regulatory.status': 'Status',
    'regulatory.version': 'Version',
    'regulatory.approved': 'Genehmigt',
    'regulatory.review': 'Überprüfung',
    'regulatory.annually': 'Jährlich',
    'regulatory.changeHistory': 'Änderungshistorie',
    'regulatory.initiallyCreated': 'Initial erstellt',
    'regulatory.dateNotAvailable': 'Datum nicht verfügbar',
    'regulatory.technicalMetadata': 'Technische Metadaten',
    'regulatory.category': 'Kategorie',
    'regulatory.type': 'Typ',
    'regulatory.tags': 'Tags',
    'regulatory.fda510kApproval': 'FDA 510(k) Zulassung',
    'regulatory.approvalGeneric': 'Zulassung',
    'regulatory.regulationGeneric': 'Verordnung',
    'regulatory.guidelineGeneric': 'Leitlinie',
    'regulatory.standardGeneric': 'Standard',
    'regulatory.safetyWarning': 'Sicherheitswarnung',
    'regulatory.regulationNumber': 'Regulierungsnummer',
    'regulatory.decisionDate': 'Entscheidungsdatum',
    'regulatory.summary': 'Zusammenfassung',
    'regulatory.id': 'ID',
    'regulatory.note': 'Hinweis',
    'regulatory.priority.high': 'Hoch',
    'regulatory.priority.normal': 'Normal',
    
    // Legal Cases
    'legal.title': 'Rechtsprechung',
    'legal.subtitle': 'Medizinrechtliche Fälle und Entscheidungen',
    'legal.court': 'Gericht',
    'legal.jurisdiction': 'Zuständigkeit',
    'legal.caseType': 'Falltyp',
    'legal.decision': 'Entscheidung',
    'legal.searchCases': 'Fälle durchsuchen...',
    'legal.viewCase': 'Fall anzeigen',
    
    // Buttons and Actions
    'action.viewAll': 'Alle anzeigen',
    'action.refresh': 'Aktualisieren',
    'action.configure': 'Konfigurieren',
    'action.test': 'Testen',
    'action.sync': 'Synchronisieren',
    'action.details': 'Details',
    'action.manage': 'Verwalten',
    'action.add': 'Hinzufügen',
    'action.remove': 'Entfernen',
    'action.update': 'Aktualisieren',
    'action.export': 'Export',
    
    // Knowledge Base specific
    'knowledge.noSummary': 'Keine Zusammenfassung verfügbar',
    'knowledge.fullContent': 'Vollständiger Inhalt',
    'knowledge.exportGenerated': 'Export generiert am',
    'search.summary': 'Zusammenfassung',
    
    // Time and Date
    'time.today': 'Heute',
    'time.yesterday': 'Gestern',
    'time.thisWeek': 'Diese Woche',
    'time.thisMonth': 'Dieser Monat',
    'time.lastMonth': 'Letzter Monat',
    'time.lastSync': 'Letzter Sync',
    'time.noSync': 'Noch kein Sync',
    
    // Metrics and Statistics
    'metrics.total': 'Gesamt',
    'metrics.active': 'Aktiv',
    'metrics.pending': 'Ausstehend',
    'metrics.completed': 'Abgeschlossen',
    'metrics.failed': 'Fehlgeschlagen',
    'metrics.success': 'Erfolgreich',
    'metrics.trend': 'Trend',
    'metrics.increase': 'Anstieg',
    'metrics.decrease': 'Rückgang',
    'metrics.stable': 'Stabil',
    
    // Subscription Plans
    'basic.updates': 'Grundlegende Updates',
    'basic.notifications': 'Email-Benachrichtigungen',
    'basic.support': 'Standard-Support',
    'professional.analytics': 'Erweiterte Analytics',
    'professional.support': 'Priority Support',
    'professional.reports': 'Custom Reports',
    'professional.api': 'API Access',
    'enterprise.unlimited': 'Unbegrenzte Zugriffe',
    'enterprise.dedicated': 'Dedicated Account Manager',
    'enterprise.custom': 'Custom Integrations',
    
    // Authentication
    'auth.loginFailed': 'Anmeldung fehlgeschlagen. Bitte versuchen Sie es erneut.',
    'auth.login': 'Anmelden',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.demo': 'Demo-Zugang',
    
    // Access Control
    'access.restricted': 'Zugriff beschränkt',
    'access.noPermission': 'Keine Berechtigung',
    'access.contactAdmin': 'Kontaktieren Sie Ihren Administrator',
    
    // Customer Portal
    'customer.dashboard': 'Kunden-Dashboard',
    'customer.portal': 'Kundenportal',
    'customer.logout': 'Abmelden',
    'customer.chat': 'Support Chat',

    // Dashboard — cards, sections, dynamic labels
    'dashboard.liveSystem': 'Live System',
    'dashboard.sourcesActive': 'Quellen aktiv',
    'dashboard.updates': 'Updates',
    'dashboard.dataSources': 'Data Sources',
    'dashboard.globalPatents': 'Global Patents',
    'dashboard.analysisPortal': 'Analyseportal',
    'dashboard.multiAgentRag': 'Multi-Agent RAG System',
    'dashboard.advancedAnalytics': 'Advanced Analytics',
    'dashboard.newsletter': 'Newsletter',
    'dashboard.marketInsights': 'Markt & Insights',
    'dashboard.professionalAnalyses': 'Professionelle Analysen',
    'dashboard.inProgress': 'In Bearbeitung',
    'dashboard.newsletterSubscriptions': 'Newsletter-Abonnements',
    'dashboard.fullyAutomated': 'Vollautomatisiert',
    'dashboard.activeSourcesGlobal': 'Aktive Datenquellen global',
    'dashboard.globalPatentDb': 'Weltweite Patentdatenbank',
    'dashboard.newIn7Days': '{{count}} neue in 7 Tagen',
    'dashboard.casesIn30Days': '{{count}} Fälle in 30 Tagen',
    'dashboard.syncRunning': 'Synchronisierung läuft',
    'dashboard.syncInitializing': 'Synchronisierung wird initialisiert',
    'dashboard.syncProgress': 'Synchronisierung {{pct}}%',
    'dashboard.fullyAnalyzed': 'Vollständig analysiert',
    'dashboard.analysisLoading': 'Analyse wird geladen…',
    'dashboard.statusUpdating': 'Status wird aktualisiert…',
    'dashboard.liveConnected': 'Live verbunden',
    'dashboard.latestRegulatoryChanges': 'Neueste regulatorische Änderungen von großen Behörden',
    'dashboard.newsletterSources': 'Newsletter Sources',
    'dashboard.autoNewsletterExtraction': 'Automatische MedTech-Newsletter für automatische Datenextraktion',
    'dashboard.officialFdaUpdates': 'Offizielle FDA Updates',
    'dashboard.emaAgency': 'Europäische Arzneimittel-Agentur',
    'dashboard.medtechIndustryNews': 'Medizintechnik-Industrie News',
    'dashboard.quickActions': 'Schnelle Aktionen',
    'dashboard.quickActionsDesc': 'Helix vereinfacht Ihre Funktionen für effiziente Aktionen',
    'dashboard.dataSourcesSync': 'Datenquellen Sync',
    'dashboard.newsletterSync': 'Newsletter Sync',
    'dashboard.structureArticles': 'Artikel strukturieren',
    'dashboard.createNewIssue': 'Neue Ausgabe erstellen',
    'dashboard.advancedTrends': 'Erweiterte Trends',
    'dashboard.adminOfficeHours': 'Direkte Administrator-Sprechzeiten',
    'dashboard.regulatoryIntelligenceSearch': 'Regulatory Intelligence Search',
    'dashboard.intelligentSearchDesc': 'Intelligente Suche in regulatorischen Dokumenten und Updates',
    'dashboard.searchMedtechDb': 'Durchsuchen Sie die umfangreichste MedTech-Wissensdatenbank mit KI-Unterstützung',
    'dashboard.searchPlaceholder': "z.B. 'Neue FDA Cybersecurity-Richtlinien für Medizingeräte'",
    'dashboard.searchButton': 'Suchen',
    'dashboard.fdaEmaWho': 'FDA, EMA, WHO',
    'dashboard.medtechSources': 'MedTech Sources',
    'dashboard.regulatoryUpdate': 'Regulatory Update',
    'dashboard.qualitySystem': 'Quality System',
    'dashboard.aktiveLabel': 'Aktiv',

    // Analytics (Ergänzungen Pass 6)
    'analytics.liveCharts': 'Live Charts',
    'analytics.realTimeMetrics': 'Echtzeit-Metriken',
    'analytics.globalInsights': 'Global Insights',
    'analytics.thirtyDays': '30 Tage',
    'analytics.export': 'Export',
    'analytics.worldwideApprovals': 'Weltweite Genehmigungen',
    'analytics.vsLastMonth': 'gegenüber letztem Monat',
    'analytics.liveUpdates': 'Live Updates',
    'analytics.trendRising': 'Trend steigend',
    'analytics.activeSourcesActive': 'Aktive Datenquellen aktiv',
    'analytics.globallyAvailable': 'Global verfügbar',
    'analytics.dataSourcesActive': 'Datenquellen aktiv',
    'analytics.realtimeSync': 'Realzeit-Sync',
    'analytics.updatesByRegion': 'Updates nach Regionen',
    'analytics.distributionByDataType': 'Verteilung nach Datentypen',
    'analytics.thirtyDayTrend': '30-Tage Trend',
    'analytics.updatesAndApprovalsOverTime': 'Updates und Genehmigungen über Zeit',
    'analytics.coverage': 'Coverage',
    'analytics.europe': 'Europa',
    'analytics.northAmerica': 'Nordamerika',
    'analytics.asiaPacific': 'Asien-Pazifik',
    'analytics.germany': 'Deutschland',
    'analytics.regulatoryUpdatesLabel': 'Regulatorische Updates',
    'analytics.legalCases': 'Rechtsfälle',
    'regulatory.deviceClass': 'Geräteklasse',
    'analytics.activeDataSources': 'Aktive Datenquellen',
    'analytics.thirtyDaysShort': '30 Tage',
    'analytics.knowledgeArticles': 'Knowledge Articles',

    // Knowledge Base (Ergänzungen Pass 6)
    'knowledge.backToDashboard': 'Zurück zum Dashboard',
    'knowledge.loadingArticles': 'Knowledge Base wird geladen',
    'knowledge.syncingArticles': 'Medizintechnik-Artikel werden synchronisiert',

    // Data Collection (Ergänzungen Pass 6)
    'dataCollection.autoSync': 'Auto-Sync',
    'dataCollection.dataQuality': 'Data Quality',
    'dataCollection.liveMonitoring': 'Live Monitoring',
    'dataCollection.dataSources': 'Data Sources',
    'dataCollection.syncHistory': 'Sync History',
    'dataCollection.settings': 'Settings',
    'dataCollection.syncAllSources': 'Sync All Sources',
    'dataCollection.addSource': 'Add Source',
    'dataCollection.regulatoryDataSources': '🏛️ Regulatorische Datenquellen',
    'dataCollection.regulatorySourcesDesc': 'Offizielle regulatorische Datenbanken (FDA, WHO, EU) für Compliance-Daten',
    'dataCollection.newsletterSourcesDesc': 'Authentische MedTech-Newsletter für automatische Inhaltsextraktion',
    'dataCollection.newsletterSync': 'Newsletter Sync',
    'dataCollection.addNewSource': 'Add New Data Source',
    'dataCollection.sourceName': 'Source Name *',
    'dataCollection.type': 'Type',
    'dataCollection.apiEndpoint': 'API Endpoint *',
    'dataCollection.description': 'Description',
    'dataCollection.noDataSources': 'No Data Sources',
    'dataCollection.addFirstSource': 'Add your first data source to start collecting regulatory data.',
    'dataCollection.addDataSource': 'Add Data Source',
    'dataCollection.synchronizationHistory': 'Synchronization History',
    'dataCollection.viewRecentActivities': 'View recent data collection activities',
    'dataCollection.viewAllLogs': 'View All Logs',
    'dataCollection.dataCollectionSettings': 'Data Collection Settings',
    'dataCollection.configureSyncParams': 'Configure synchronization and collection parameters',
    'dataCollection.autoSyncFreq': 'Automatic Sync Frequency',
    'dataCollection.retryFailedSyncs': 'Retry Failed Syncs',
    'dataCollection.realTimeMonitoring': 'Real-time Monitoring',
    'dataCollection.monitorImmediateUpdates': 'Monitor data sources for immediate updates',
    'dataCollection.dataValidation': 'Data Validation',
    'dataCollection.autoValidateIncoming': 'Automatically validate incoming regulatory data',
    'dataCollection.saveSettings': 'Save Settings',
    'dataCollection.resetDefaults': 'Reset to Defaults',
    'dataCollection.regulatoryData': 'Regulatorische Daten',
    'dataCollection.neverSynced': 'Never Synced',
    'dataCollection.active': 'Active',
    'dataCollection.recent': 'Recent',
    'dataCollection.stale': 'Stale',
    'dataCollection.success': 'Success',
    'dataCollection.loadMoreHistory': 'Load More History'
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.analytics': 'Reports & Analytics',
    'nav.dataCollection': 'Data Collection',
    'nav.newsletterAdmin': 'Newsletter Management',
    'nav.emailManagement': 'Email Management',
    'nav.knowledgeBase': 'Knowledge Base',
    'nav.regulatoryUpdates': 'Regulatory Updates',
    'nav.legalCases': 'Legal Cases',
    'nav.globalApprovals': 'Global Approvals',
    'nav.ongoingApprovals': 'Ongoing Approvals',
    'nav.intelligentSearch': 'Intelligent Search',
    'nav.syncManager': 'Sync Management',
    'nav.globalSources': 'Global Sources',
    'nav.newsletterManager': 'Newsletter Manager',
    'nav.historicalData': 'Historical Data',
    'nav.customerManagement': 'Customer Management',
    'nav.userManagement': 'User Management',
    'nav.systemAdmin': 'System Administration',
    'nav.auditLogs': 'Audit Logs',
    
    // Navigation Sections
    'nav.sections.overview': 'OVERVIEW & CONTROL',
    'nav.sections.dataManagement': 'DATA MANAGEMENT',
    'nav.sections.compliance': 'COMPLIANCE & REGULATION',
    'nav.sections.approvals': 'APPROVALS & REGISTRATION',
    'nav.sections.advanced': 'ADVANCED',
    'nav.sections.projects': 'PROJECTS & FILES',
    'nav.sections.standards': 'STANDARDS & NORMS',

    // Assistants & Sub-Items
    'nav.regulatoryAssistant': 'Regulatory Assistant',
    'nav.approvalAssistant': 'Approval Assistant',
    'nav.projectAssistant': 'Project Assistant',
    'nav.formAssistant': 'Form Assistant',
    'nav.projectOverview': 'Project Overview',
    'nav.newProject': 'New Project File',
    'nav.projectMDR': 'Project File (MDR)',
    'nav.globalPatents': 'Global Patents',
    'nav.patentSearch': 'Patent Search',
    'nav.legalAssistant': 'Legal Assistant',
    'nav.dataSourcesDetails': 'Data Source Details',
    'nav.dataCollectionCenter': 'Data Collection Center',
    'nav.advancedAnalysis': 'Advanced Analysis',
    'nav.marketInsights': 'Market & Insights',
    'nav.aiInsights': 'AI Insights',

    // Standards
    'nav.standards.iso': 'ISO Standards',
    'nav.standards.iec': 'IEC Standards',
    'nav.standards.astm': 'ASTM Standards',
    'nav.standards.en': 'EN Standards',
    'nav.standards.aami': 'AAMI Standards',
    'nav.standards.mdr': 'EU MDR 2017/745',

    // Sidebar UI
    'sidebar.search.title': 'Intelligent Search',
    'sidebar.search.placeholder': 'Search regulations, devices, approvals...',
    'sidebar.search.hint': 'Press Enter to search',
    'sidebar.systemStatus': 'System Status',
    'sidebar.dataSources': 'Data Sources',
    'sidebar.active': '21 Active',
    'sidebar.logout': 'System Logout',
    'sidebar.customerPortal': 'Customer Portal',
    'sidebar.openCustomerPortal': 'Open Customer Portal',
    'sidebar.profile': 'Profile',
    'sidebar.settings': 'Settings',
    'sidebar.signOut': 'Sign Out',
    'sidebar.tenantLogin': 'Tenant Login',
    'sidebar.customerArea': 'Customer Area',
    'sidebar.supportChat': 'Support Chat',
    'sidebar.openMenu': 'Open menu',
    'sidebar.brandSubtitle': 'MedTech Intelligence',
    'sidebar.brandName': 'Helix',
    'sidebar.poweredBy': 'Powered by Helix Platform',
    'sidebar.footerVersion': 'Helix Platform v2.0',
    'sidebar.footerCopyright': '© 2025 MedTech Intelligence',

    // Search
    'search.askQuestion': 'Ask a question...',
    
    // Status
    'status.label': 'Status',
    'status.online': 'Online',
    'status.dataSources': '46 Data Sources',
    
    // Common
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.download': 'Download',
    'common.export': 'Export',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.pending': 'Pending',
    'common.completed': 'Completed',
    'common.date': 'Date',
    'common.status': 'Status',
    'common.priority': 'Priority',
    'common.region': 'Region',
    'common.category': 'Category',
    'common.source': 'Source',
    'common.language': 'Language',
    
    // Dashboard
    'dashboard.title': 'Helix Regulatory Intelligence',
    'dashboard.subtitle': 'Comprehensive Medical Device Regulatory Platform',
    'dashboard.totalUpdates': 'Total Updates',
    'dashboard.legalCases': 'Legal Cases',
    'dashboard.knowledgeArticles': 'Knowledge Articles',
    'dashboard.activeDataSources': 'Active Data Sources',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.welcomeBack': 'Welcome Back',
    
    // Intelligent Search
    'search.title': 'Intelligent Search',
    'search.subtitle': 'AI-powered search across all Helix data sources',
    'search.placeholder': 'e.g. "MDR requirements for Class III devices"',
    'search.searching': 'Searching...',
    'search.results': 'Search Results',
    'search.aiAnswer': 'AI Answer',
    'search.noResults': 'No results found',
    'search.confidence': 'Confidence',
    'search.relevance': 'Relevance',
    'search.databaseResults': 'Database Results',
    'search.aiResults': 'AI Results',
    
    // Analytics
    'analytics.title': 'Analytics Intelligence',
    'analytics.subtitle': 'Comprehensive analysis of regulatory data landscape',
    'analytics.totalUpdates': 'Total Updates',
    'analytics.pendingApprovals': 'Pending Approvals',
    'analytics.regionalDistribution': 'Regional Distribution',
    'analytics.categoryBreakdown': 'Category Breakdown',
    'analytics.sourcePerformance': 'Data Sources Performance',
    
    // Knowledge Base
    'knowledge.title': 'Knowledge Base',
    'knowledge.subtitle': 'Medical device knowledge articles from authentic sources',
    'knowledge.totalArticles': 'Total Articles',
    'knowledge.activeSources': 'Active Sources',
    'knowledge.regions': 'Regions',
    'knowledge.languages': 'Languages',
    'knowledge.searchPlaceholder': 'Search for articles...',
    
    // Newsletter Admin
    'newsletter.title': 'Newsletter Administration',
    'newsletter.subtitle': 'Manage authentic newsletter sources',
    'newsletter.addSource': 'Add New Source',
    'newsletter.configuredSources': 'Configured Newsletter Sources',
    'newsletter.authenticSources': 'Authentic Newsletter Sources',
    
    // Data Collection
    'dataCollection.activeSources': 'Active Sources',
    'dataCollection.syncStatus': 'Sync Status',
    'dataCollection.lastSync': 'Last Sync',
    'dataCollection.manageSource': 'Manage Source',
    'dataCollection.runningSyncs': 'Running Syncs',
    'dataCollection.pendingSyncs': 'Pending Syncs',
    'dataCollection.recentSyncs': 'Recent Syncs',
    
    // Regulatory Updates
    'regulatory.title': 'Regulatory Updates',
    'regulatory.subtitle': 'Current regulations and guidelines for medical devices',
    'regulatory.region': 'Region',
    'regulatory.authority': 'Authority',
    'regulatory.published': 'Published',
    'regulatory.viewDetails': 'View Details',
    'regulatory.searchUpdates': 'Search updates...',
    'regulatory.allRegions': 'All Regions',
    'regulatory.allAuthorities': 'All Authorities',
    'regulatory.allCategories': 'All Categories',
    'regulatory.allPriorities': 'All Priorities',
    'regulatory.allTypes': 'All Types',
    'regulatory.resetFilters': 'Reset Filters',
    'regulatory.loadingUpdates': 'Loading updates...',
    'regulatory.noUpdatesFound': 'No updates found',
    'regulatory.tryDifferentSearch': 'Try a different search or filter',
    'regulatory.resultsCount': 'results',
    'regulatory.updatesOf': 'of',
    'regulatory.newBadge': 'New',
    'regulatory.type.approval': 'Approvals',
    'regulatory.type.regulation': 'Regulations',
    'regulatory.type.guidance': 'Guidelines',
    'regulatory.type.standard': 'Standards',
    'regulatory.type.alert': 'Alerts',
    'regulatory.tab.document': 'Document',
    'regulatory.tab.action': 'Action Required',
    'regulatory.tab.implementation': 'Implementation',
    'regulatory.tab.control': 'Document Control',
    'regulatory.tab.metadata': 'Metadata',
    'regulatory.documentDetails': 'Document Details',
    'regulatory.documentType': 'Document Type',
    'regulatory.jurisdiction': 'Jurisdiction',
    'regulatory.kNumber': 'K-Number',
    'regulatory.applicant': 'Applicant',
    'regulatory.productCode': 'Product Code',
    'regulatory.publishedAt': 'Published',
    'regulatory.effectiveFrom': 'Effective From',
    'regulatory.descriptionJustification': 'Description & Justification',
    'regulatory.descriptionHint': 'This description explains the background, reasons, and impact of this regulatory change.',
    'regulatory.sourcesAndDocs': 'Sources & Official Documents',
    'regulatory.dataSource': 'Data Source',
    'regulatory.officialSource': 'Official Source',
    'regulatory.documentDownload': 'Document Download',
    'regulatory.downloadOfficialDoc': 'Download Official Document',
    'regulatory.accompanyingDocs': 'Accompanying Documents & Guides',
    'regulatory.openDocument': 'Open Document',
    'regulatory.fullDocumentContent': 'Full Document Content',
    'regulatory.actionRequired': 'Action Required',
    'regulatory.measuresRequired': 'Measures required for compliance',
    'regulatory.deadline': 'Deadline',
    'regulatory.affectedProducts': 'Affected Products',
    'regulatory.guidelineDocuments': 'Guideline Documents',
    'regulatory.noActionRequired': 'No Action Required',
    'regulatory.noImmediateMeasures': 'This document does not require immediate measures.',
    'regulatory.implementationGuide': 'Implementation Guide',
    'regulatory.noImplementationGuide': 'No implementation guide available',
    'regulatory.timeframe': 'Timeframe',
    'regulatory.estimatedTime': 'Estimated Implementation Time',
    'regulatory.documentLifecycle': 'Document Lifecycle',
    'regulatory.status': 'Status',
    'regulatory.version': 'Version',
    'regulatory.approved': 'Approved',
    'regulatory.review': 'Review',
    'regulatory.annually': 'Annually',
    'regulatory.changeHistory': 'Change History',
    'regulatory.initiallyCreated': 'Initially Created',
    'regulatory.dateNotAvailable': 'Date not available',
    'regulatory.technicalMetadata': 'Technical Metadata',
    'regulatory.category': 'Category',
    'regulatory.type': 'Type',
    'regulatory.tags': 'Tags',
    'regulatory.fda510kApproval': 'FDA 510(k) Approval',
    'regulatory.approvalGeneric': 'Approval',
    'regulatory.regulationGeneric': 'Regulation',
    'regulatory.guidelineGeneric': 'Guideline',
    'regulatory.standardGeneric': 'Standard',
    'regulatory.safetyWarning': 'Safety Warning',
    'regulatory.regulationNumber': 'Regulation Number',
    'regulatory.decisionDate': 'Decision Date',
    'regulatory.summary': 'Summary',
    'regulatory.id': 'ID',
    'regulatory.note': 'Note',
    'regulatory.priority.high': 'High',
    'regulatory.priority.normal': 'Normal',
    
    // Legal Cases
    'legal.title': 'Legal Cases',
    'legal.subtitle': 'Medical law cases and decisions',
    'legal.court': 'Court',
    'legal.jurisdiction': 'Jurisdiction',
    'legal.caseType': 'Case Type',
    'legal.decision': 'Decision',
    'legal.searchCases': 'Search cases...',
    'legal.viewCase': 'View Case',
    
    // Buttons and Actions
    'action.viewAll': 'View All',
    'action.refresh': 'Refresh',
    'action.configure': 'Configure',
    'action.test': 'Test',
    'action.sync': 'Sync',
    'action.details': 'Details',
    'action.manage': 'Manage',
    'action.add': 'Add',
    'action.remove': 'Remove',
    'action.update': 'Update',
    'action.export': 'Export',
    
    // Knowledge Base specific
    'knowledge.noSummary': 'No summary available',
    'knowledge.fullContent': 'Full Content',
    'knowledge.exportGenerated': 'Export generated on',
    'search.summary': 'Summary',
    
    // Time and Date
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
    'time.thisWeek': 'This Week',
    'time.thisMonth': 'This Month',
    'time.lastMonth': 'Last Month',
    'time.lastSync': 'Last Sync',
    'time.noSync': 'No Sync Yet',
    
    // Metrics and Statistics
    'metrics.total': 'Total',
    'metrics.active': 'Active',
    'metrics.pending': 'Pending',
    'metrics.completed': 'Completed',
    'metrics.failed': 'Failed',
    'metrics.success': 'Successful',
    'metrics.trend': 'Trend',
    'metrics.increase': 'Increase',
    'metrics.decrease': 'Decrease',
    'metrics.stable': 'Stable',
    
    // Subscription Plans
    'basic.updates': 'Basic Updates',
    'basic.notifications': 'Email Notifications',
    'basic.support': 'Standard Support',
    'professional.analytics': 'Advanced Analytics',
    'professional.support': 'Priority Support',
    'professional.reports': 'Custom Reports',
    'professional.api': 'API Access',
    'enterprise.unlimited': 'Unlimited Access',
    'enterprise.dedicated': 'Dedicated Account Manager',
    'enterprise.custom': 'Custom Integrations',
    
    // Authentication
    'auth.loginFailed': 'Login failed. Please try again.',
    'auth.login': 'Login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.demo': 'Demo Access',
    
    // Access Control
    'access.restricted': 'Access Restricted',
    'access.noPermission': 'No Permission',
    'access.contactAdmin': 'Contact your administrator',
    
    // Customer Portal
    'customer.dashboard': 'Customer Dashboard',
    'customer.portal': 'Customer Portal',
    'customer.logout': 'Logout',
    'customer.chat': 'Support Chat',

    // Dashboard — cards, sections, dynamic labels
    'dashboard.liveSystem': 'Live System',
    'dashboard.sourcesActive': 'Sources Active',
    'dashboard.updates': 'Updates',
    'dashboard.dataSources': 'Data Sources',
    'dashboard.globalPatents': 'Global Patents',
    'dashboard.analysisPortal': 'Analysis Portal',
    'dashboard.multiAgentRag': 'Multi-Agent RAG System',
    'dashboard.advancedAnalytics': 'Advanced Analytics',
    'dashboard.newsletter': 'Newsletter',
    'dashboard.marketInsights': 'Market & Insights',
    'dashboard.professionalAnalyses': 'Professional Analyses',
    'dashboard.inProgress': 'In Progress',
    'dashboard.newsletterSubscriptions': 'Newsletter Subscriptions',
    'dashboard.fullyAutomated': 'Fully Automated',
    'dashboard.activeSourcesGlobal': 'Active Data Sources Global',
    'dashboard.globalPatentDb': 'Worldwide Patent Database',
    'dashboard.newIn7Days': '{{count}} new in 7 days',
    'dashboard.casesIn30Days': '{{count}} cases in 30 days',
    'dashboard.syncRunning': 'Sync running',
    'dashboard.syncInitializing': 'Initializing sync',
    'dashboard.syncProgress': 'Sync {{pct}}%',
    'dashboard.fullyAnalyzed': 'Fully analyzed',
    'dashboard.analysisLoading': 'Loading analysis…',
    'dashboard.statusUpdating': 'Updating status…',
    'dashboard.liveConnected': 'Live connected',
    'dashboard.latestRegulatoryChanges': 'Latest regulatory changes from major authorities',
    'dashboard.newsletterSources': 'Newsletter Sources',
    'dashboard.autoNewsletterExtraction': 'Automated MedTech newsletters for automatic data extraction',
    'dashboard.officialFdaUpdates': 'Official FDA Updates',
    'dashboard.emaAgency': 'European Medicines Agency',
    'dashboard.medtechIndustryNews': 'MedTech Industry News',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.quickActionsDesc': 'Helix simplifies your functions for efficient actions',
    'dashboard.dataSourcesSync': 'Data Sources Sync',
    'dashboard.newsletterSync': 'Newsletter Sync',
    'dashboard.structureArticles': 'Structure Articles',
    'dashboard.createNewIssue': 'Create New Issue',
    'dashboard.advancedTrends': 'Advanced Trends',
    'dashboard.adminOfficeHours': 'Direct Administrator Office Hours',
    'dashboard.regulatoryIntelligenceSearch': 'Regulatory Intelligence Search',
    'dashboard.intelligentSearchDesc': 'Intelligent search across regulatory documents and updates',
    'dashboard.searchMedtechDb': 'Search the most comprehensive MedTech knowledge base with AI support',
    'dashboard.searchPlaceholder': "e.g. 'New FDA cybersecurity guidelines for medical devices'",
    'dashboard.searchButton': 'Search',
    'dashboard.fdaEmaWho': 'FDA, EMA, WHO',
    'dashboard.medtechSources': 'MedTech Sources',
    'dashboard.regulatoryUpdate': 'Regulatory Update',
    'dashboard.qualitySystem': 'Quality System',
    'dashboard.aktiveLabel': 'Active',

    // Analytics (Pass 6 additions)
    'analytics.liveCharts': 'Live Charts',
    'analytics.realTimeMetrics': 'Real-Time Metrics',
    'analytics.globalInsights': 'Global Insights',
    'analytics.thirtyDays': '30 Days',
    'analytics.export': 'Export',
    'analytics.worldwideApprovals': 'Worldwide Approvals',
    'analytics.vsLastMonth': 'vs. last month',
    'analytics.liveUpdates': 'Live Updates',
    'analytics.trendRising': 'Trend Rising',
    'analytics.activeSourcesActive': 'Active Data Sources Active',
    'analytics.globallyAvailable': 'Globally Available',
    'analytics.dataSourcesActive': 'Data Sources Active',
    'analytics.realtimeSync': 'Real-Time Sync',
    'analytics.updatesByRegion': 'Updates by Region',
    'analytics.distributionByDataType': 'Distribution by Data Type',
    'analytics.thirtyDayTrend': '30-Day Trend',
    'analytics.updatesAndApprovalsOverTime': 'Updates and Approvals Over Time',
    'analytics.coverage': 'Coverage',
    'analytics.europe': 'Europe',
    'analytics.northAmerica': 'North America',
    'analytics.asiaPacific': 'Asia-Pacific',
    'analytics.germany': 'Germany',
    'analytics.regulatoryUpdatesLabel': 'Regulatory Updates',
    'analytics.legalCases': 'Legal Cases',
    'analytics.activeDataSources': 'Active Data Sources',
    'analytics.thirtyDaysShort': '30 Days',
    'analytics.knowledgeArticles': 'Knowledge Articles',

    // Knowledge Base (Pass 6 additions)
    'knowledge.backToDashboard': 'Back to Dashboard',
    'knowledge.loadingArticles': 'Loading Knowledge Base',
    'knowledge.syncingArticles': 'Syncing MedTech articles',

    // Data Collection (Pass 6 additions)
    'dataCollection.title': 'Data Collection Center',
    'dataCollection.subtitle': 'Monitor and manage {{count}} global regulatory data sources with Executive-Controls',
    'dataCollection.autoSync': 'Auto-Sync',
    'dataCollection.dataQuality': 'Data Quality',
    'dataCollection.liveMonitoring': 'Live Monitoring',
    'dataCollection.dataSources': 'Data Sources',
    'dataCollection.syncHistory': 'Sync History',
    'dataCollection.settings': 'Settings',
    'dataCollection.syncAllSources': 'Sync All Sources',
    'dataCollection.addSource': 'Add Source',
    'dataCollection.regulatoryDataSources': '🏛️ Regulatory Data Sources',
    'dataCollection.regulatorySourcesDesc': 'Official regulatory databases (FDA, WHO, EU) for compliance data',
    'dataCollection.newsletterSources': '📧 Newsletter Sources',
    'dataCollection.newsletterSourcesDesc': 'Authentic MedTech newsletters for automatic content extraction',
    'dataCollection.syncNow': 'Sync Now',
    'dataCollection.newsletterSync': 'Newsletter Sync',
    'dataCollection.addNewSource': 'Add New Data Source',
    'dataCollection.sourceName': 'Source Name *',
    'dataCollection.type': 'Type',
    'dataCollection.apiEndpoint': 'API Endpoint *',
    'dataCollection.description': 'Description',
    'dataCollection.noDataSources': 'No Data Sources',
    'dataCollection.addFirstSource': 'Add your first data source to start collecting regulatory data.',
    'dataCollection.addDataSource': 'Add Data Source',
    'dataCollection.synchronizationHistory': 'Synchronization History',
    'dataCollection.viewRecentActivities': 'View recent data collection activities',
    'dataCollection.viewAllLogs': 'View All Logs',
    'dataCollection.dataCollectionSettings': 'Data Collection Settings',
    'dataCollection.configureSyncParams': 'Configure synchronization and collection parameters',
    'dataCollection.autoSyncFreq': 'Automatic Sync Frequency',
    'dataCollection.retryFailedSyncs': 'Retry Failed Syncs',
    'dataCollection.realTimeMonitoring': 'Real-time Monitoring',
    'dataCollection.monitorImmediateUpdates': 'Monitor data sources for immediate updates',
    'dataCollection.dataValidation': 'Data Validation',
    'dataCollection.autoValidateIncoming': 'Automatically validate incoming regulatory data',
    'dataCollection.saveSettings': 'Save Settings',
    'dataCollection.resetDefaults': 'Reset to Defaults',
    'dataCollection.regulatoryData': 'Regulatory Data',
    'dataCollection.neverSynced': 'Never Synced',
    'dataCollection.active': 'Active',
    'dataCollection.recent': 'Recent',
    'dataCollection.stale': 'Stale',
    'dataCollection.success': 'Success',
    'dataCollection.loadMoreHistory': 'Load More History'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('helix-language');
    return (saved as Language) || 'de';
  });

  useEffect(() => {
    localStorage.setItem('helix-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}